/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DentistaRomaSurIndexRouteImport } from './routes/dentista-roma-sur/index'
import { Route as DisenoDeSonrisaCdmxIndexRouteImport } from './routes/diseno-de-sonrisa-cdmx/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistaRomaSurIndexRoute = DentistaRomaSurIndexRouteImport.update({
  id: '/dentista-roma-sur/',
  path: '/dentista-roma-sur/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoDeSonrisaCdmxIndexRoute =
  DisenoDeSonrisaCdmxIndexRouteImport.update({
    id: '/diseno-de-sonrisa-cdmx/',
    path: '/diseno-de-sonrisa-cdmx/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dentista-roma-sur/': typeof DentistaRomaSurIndexRoute
  '/diseno-de-sonrisa-cdmx/': typeof DisenoDeSonrisaCdmxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dentista-roma-sur': typeof DentistaRomaSurIndexRoute
  '/diseno-de-sonrisa-cdmx': typeof DisenoDeSonrisaCdmxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dentista-roma-sur/': typeof DentistaRomaSurIndexRoute
  '/diseno-de-sonrisa-cdmx/': typeof DisenoDeSonrisaCdmxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dentista-roma-sur/' | '/diseno-de-sonrisa-cdmx/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dentista-roma-sur' | '/diseno-de-sonrisa-cdmx'
  id: '__root__' | '/' | '/dentista-roma-sur/' | '/diseno-de-sonrisa-cdmx/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DentistaRomaSurIndexRoute: typeof DentistaRomaSurIndexRoute
  DisenoDeSonrisaCdmxIndexRoute: typeof DisenoDeSonrisaCdmxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentista-roma-sur/': {
      id: '/dentista-roma-sur/'
      path: '/dentista-roma-sur'
      fullPath: '/dentista-roma-sur/'
      preLoaderRoute: typeof DentistaRomaSurIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-de-sonrisa-cdmx/': {
      id: '/diseno-de-sonrisa-cdmx/'
      path: '/diseno-de-sonrisa-cdmx'
      fullPath: '/diseno-de-sonrisa-cdmx/'
      preLoaderRoute: typeof DisenoDeSonrisaCdmxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DentistaRomaSurIndexRoute: DentistaRomaSurIndexRoute,
  DisenoDeSonrisaCdmxIndexRoute: DisenoDeSonrisaCdmxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
